In [1]:
# Importing packages
import pandas as pd

In [2]:
# Importing Data
education = pd.read_csv("education.csv")
vaccineByCounty = pd.read_csv("vaccinebycounty.csv")
unemploymentReport = pd.read_csv("Unemployment_report - Sheet1.csv")
demVsrep = pd.read_csv("democratic_vs_republican_votes_by_usa_state_2020.csv")

In [3]:
# ViewData
education

,"Educational attainment for adults age 25 and older for the U.S., States, and counties, 1970-2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54
0,"Sources: U.S. Census Bureau, 1970, 1980, 1990,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"For definitions of rural classifications, see ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"This table was prepared by USDA, Economic Rese...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Federal Information Processing Standards (FIPS...,State,Area name,2003 Rural-Uban Continuum Code,2003 Urban Influence Code,2013 Rural-Urban Continuum Code,2013 Urban Influence Code,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970",...,Percent of adults completing some college or a...,Percent of adults with a bachelor's degree or ...,"Less than a high school diploma, 2016-20","High school diploma only, 2016-20","Some college or associate's degree, 2016-20","Bachelor's degree or higher, 2016-20",Percent of adults with less than a high school...,Percent of adults with a high school diploma o...,Percent of adults completing some college or a...,Percent of adults with a bachelor's degree or ...
4,00000,US,United States,NaN,NaN,NaN,NaN,"52,373,312","34,158,051","11,650,730",...,7.6,28.2,"25,562,680","59,421,420","64,496,416","73,356,320",11.5,26.7,28.9,32.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3284,72145,PR,Vega Baja Municipio,1,1,1,1,NaN,NaN,NaN,...,10.8,17.4,"9,683","10,459","8,550","7,948",26.4,28.5,23.3,21.7
3285,72147,PR,Vieques Municipio,7,12,7,12,NaN,NaN,NaN,...,6.1,13.7,"1,755","2,726",735,782,29.3,45.4,12.3,13.0
3286,72149,PR,Villalba Municipio,2,2,2,2,NaN,NaN,NaN,...,8.5,14.2,"3,240","5,624","3,210","2,970",21.5,37.4,21.3,19.7
3287,72151,PR,Yabucoa Municipio,1,1,1,1,NaN,NaN,NaN,...,7.7,13.8,"6,678","6,140","6,728","4,186",28.1,25.9,28.3,17.6
3288,72153,PR,Yauco Municipio,3,2,2,2,NaN,NaN,NaN,...,6.2,16.3,"6,126","8,760","4,221","6,156",24.2,34.7,16.7,24.4

In [4]:

education = education.iloc[3:]
ed = education.reset_index()
ed.drop(columns = ['index'])
ed.rename(columns=ed.iloc[0], inplace = True)
ed = ed.drop(3, axis = 1)
ed = ed.dropna()
ed = ed.drop(0)
ed =ed.reset_index(drop =True)
ed

,Federal Information Processing Standards (FIPS) Code,State,Area name,2003 Rural-Uban Continuum Code,2003 Urban Influence Code,2013 Rural-Urban Continuum Code,2013 Urban Influence Code,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970",...,"Percent of adults completing some college or associate's degree, 2007-11",Percent of adults with a bachelor's degree or higher 2007-11,"Less than a high school diploma, 2016-20","High school diploma only, 2016-20","Some college or associate's degree, 2016-20","Bachelor's degree or higher, 2016-20","Percent of adults with less than a high school diploma, 2016-20","Percent of adults with a high school diploma only, 2016-20","Percent of adults completing some college or associate's degree, 2016-20",Percent of adults with a bachelor's degree or higher 2016-20
0,01001,AL,Autauga County,2,2,2,2,"6,611","3,757",933,...,7.6,21.6,"4,273","11,880","10,986","10,721",11.3,31.4,29.0,28.3
1,01003,AL,Baldwin County,4,5,3,2,"18,726","8,426","2,334",...,7.9,27.2,"14,823","42,272","48,832","49,636",9.5,27.2,31.4,31.9
2,01005,AL,Barbour County,6,6,6,6,"8,120","2,242",581,...,6.6,13.9,"4,497","6,361","4,872","2,067",25.3,35.7,27.4,11.6
3,01007,AL,Bibb County,1,1,1,1,"5,272","1,402",238,...,6.8,9.8,"3,056","7,206","3,911","1,814",19.1,45.1,24.5,11.3
4,01009,AL,Blount County,1,1,1,1,"10,677","3,440",626,...,6.5,11.3,"6,838","13,975","13,725","5,276",17.2,35.1,34.5,13.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56037,WY,Sweetwater County,5,8,5,8,"4,393","3,731",986,...,10.8,17.0,"2,098","9,115","11,034","5,989",7.4,32.3,39.1,21.2
3120,56039,WY,Teton County,7,8,7,8,708,908,524,...,3.5,52.7,945,"2,778","4,270","9,789",5.3,15.6,24.0,55.1
3121,56041,WY,Uinta County,7,8,7,8,"1,569","1,517",445,...,8.8,18.4,903,"4,931","4,758","2,501",6.9,37.7,36.3,19.1
3122,56043,WY,Washakie County,7,11,7,11,"1,572","1,437",590,...,9.1,22.6,441,"1,587","2,174","1,313",8.0,28.8,39.4,23.8
3123,56045,WY,Weston County,7,9,7,9,"1,428","1,247",398,...,5.9,18.4,329,"1,882","1,874",848,6.7,38.2,38.0,17.2